### ISSUE TITLE
[design] LevenAndPFSettingView 내 스와이프 액션의 존재감 향상 

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#162]
### 작업에 대한 간단한 설명
- 스와이프’라는 글자를 넣어놨으나 스와이프 대신 성공, 실패 버튼을 누르는 경우가 꽤 많았음

### TODO
- [ ] 스와이프 액션의 존재를 알려줄 수 있는 UI 개선 반영

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.

**Comment by yeniful** [comment]
@RuyHa 가 온보딩을 만들어서 개선해준 내용으로 이슈 닫겠습니다!
