### ISSUE TITLE
[bug] VideoCollectionView 편집 취소 시 네비게이션바에 잘못된 정보가 표시

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#277]
### 어떤 버그(에러)가 발생했나요?
- VideoCollectionView에서 편집 취소 시 네비게이션바에 잘못된 정보가 표시됩니다.

### 버그 확인을 위한 Sequence 설명
1. VideoCollectionView에 들어간다.
2. 편집 상태로 들어간다.
3. 취소로 편집 상태를 종료한다.
4. VideoCollectionView에서 편집 취소 시 네비게이션바 좌측 아이템이 잘못 표시되고 있음.
![Simulator Screen Recording - iPhone 13 Pro + 6 44mm - 2022-11-27 at 23 11 35](https://user-images.githubusercontent.com/39216546/204139722-c03679bd-a5b8-4cf0-8c36-79975cc21291.gif)

### 버그 발생 원인 추측
- 편집 / 취소 전환 시 네비게이션바 전환을 제대로 적용하지 않음

### 버그 최초 발견자
- @sm-amoled 

### 버그 FIX 담당자
- @인물 멘션

**Comment by RuyHa** [comment]
해당 이슈 수정 완료했습니다. 이슈 클로즈 할게요
