### ISSUE TITLE
[style] 앱 Alert 문구 수정 및 버튼 디테일 사항 반영

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#315]
### 작업에 대한 간단한 설명
**`1.2.0` 배포를 위한 디테일 작업**
1. `RouteFindingCameraViewController`의 좌상단 `X버튼` 색상 변경
2. Alert창 메세지 수정

### TODO
- [x] `RouteFindingCameraViewController`의 좌상단 `X버튼` 색상 변경 
- [x] Alert창 메세지 수정

### 작업 일정
2022.11.30 - 2022.11.30

**Comment by commitcomplete** [comment]
앱의 어떤부분에 대한 디테일반영인지 제목에도 표시하면 더 좋을것 같아요:)
