### ISSUE TITLE
[fix] 카메라 사용권한 체크 후 refresh 이슈

### ISSUE THREAD

**Issue by commitcomplete** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#320]
### 어떤 버그(에러)가 발생했나요?
- 루트파인딩을 생성하기 위하여 카메라에 처음 접근시 권한 설정창이 생성됩니다.
- 설정창에서 모든 권한을 허용하였지만 바로 카메라 세션이 실행되지 않아 불편함이 있습니다.

### 버그 확인을 위한 Sequence 설명
1. 루트파인딩 생성 버튼 (카메라 버튼)을 누른다.
2. 모든 권한을 허용한다. (앱의 첫 권한 허용시 발생 - 기존에 권한을 취소하였다가 다시 허용하는 경우는 아님)
3. 버그를 발견한다.

### 버그 발생 원인 추측
- UserPermission에 변화가 생기면 처리하여 카메사 세션을 실행시키는 구문이 필요할 듯 합니다.

### 버그 최초 발견자
- @commitcomplete 

### 버그 FIX 담당자
- @jeong-hyeonHwang

**Comment by jeong-hyeonHwang** [comment]
확인했습니다! `RouteFindingCameraViewController`에서 부가적으로 발생하는 문제들에 대해서도 해당 이슈로 묶어서 함게 픽스하겠습니다!
