### ISSUE TITLE
[fix] 볼더링 비디오 업로드후 스와이프 단계에서 삭제 버튼 연속 클릭시 앱 종료

### ISSUE THREAD

**Issue by commitcomplete** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#321]
### 어떤 버그(에러)가 발생했나요?
- 보더링 비디오 업로드후 스와이프 단계에서 삭제 버튼 연속 클릭시 앱 종료

### 버그 확인을 위한 Sequence 설명
1. 보더링 비디오를 업로드한다.
2. 삭제 버튼을 연속으로 누른다.

### 버그 발생 원인 추측
- 비동기 처리가 필요할듯 합니다.

### 버그 최초 발견자
- @commitcomplete 

### 버그 FIX 담당자
- @인물 멘션

**Comment by RuyHa** [comment]
좋은!! 바로 수정하겠습니다~~
